"
Gun and left arm from Itch.io (free)
180@182 extent
"
Class {
	#name : 'GunFire',
	#superclass : 'B5Image',
	#traits : 'BlaustoClickFocus',
	#classTraits : 'BlaustoClickFocus classTrait',
	#category : 'Blausto5-elPistolero',
	#package : 'Blausto5',
	#tag : 'elPistolero'
}

{ #category : 'initialization' }
GunFire >> initialize [

	super initialize.
	self fromFilePath:
		'/Users/domenicocipriani/MyStuff/coding/pbpistolero/colpoDiPistola.png' ";
		position: 0 @ 120"
]
